import type { Metadata } from "next";
import React from "react";
import Navbar from "@/globals/navbar/Navbar";
import "./globals.css";
import { navbar } from "@/data/data";
import { Poppins } from "next/font/google";
import Starfield from "@/globals/StarField";
import { Toaster } from "@/components/ui/toaster"
import { SpeedInsights } from "@vercel/speed-insights/next"

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Harshal Dulera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Starfield
          starCount={2000}
          starColor={[255, 255, 255]}
          speedFactor={0.05}
          backgroundColor="black"
        />
        <Navbar
          logo={navbar.logo}
          title={navbar.title}
          links={navbar.links}
          name={navbar.name}
        />
        {children}
        <Toaster />
        <SpeedInsights />
      </body>
    </html>
  );
}
