import type { Metadata } from "next";
import React from "react";
import Navbar from "@/globals/navbar/Navbar";
import "./globals.css";
import { navbar } from "@/data/data";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar
          logo={navbar.logo}
          title={navbar.title}
          links={navbar.links}
          name={navbar.name}
        />
        {children}
      </body>
    </html>
  );
}
